name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Worker
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Ensure wrangler is available
      - name: Install Wrangler CLI
        run: npm install -g wrangler

      # Set CLOUDFLARE_API_TOKEN as an environment variable
      - name: Set Cloudflare API Token
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: echo "CLOUDFLARE_API_TOKEN is set"

      # Authenticate with Cloudflare and publish worker
      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      # Debug step to ensure Wrangler works
      - name: Debug Wrangler
        run: wrangler --version